// ignore_for_file: file_names
import 'dart:convert';

import 'package:bootstrap_icons/bootstrap_icons.dart';
import 'package:bug_search/src/functions/get_results.dart';
import 'package:bug_search/src/models/bsLogo.dart';
import 'package:bug_search/src/models/searchBar.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart';

import '../../models/switch_button.dart';

class SearchPage extends StatefulWidget {
  const SearchPage({super.key});

  @override
  State<SearchPage> createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
  bool isSwitched = false;
  bool onClick = false;
  bool _isTapped = true;
  bool _isTapped1 = false;
  bool _isTapped2 = false;
  bool _isTapped3 = false;

  List<dynamic> resultsFromJson = [];

  /* Future<void> getJson() async {
    try {
      const url =
          'https://dbc8-2804-c2c-cf03-cdb8-71a4-b78-e6ec-7cf7.ngrok-free.app/';
      final data = await Autogenerated.fetchData(url);
      print('PRINTING DATA');
      print(data.searchResults);
    } catch (e) {
      print('ERRO! $e');
    }
  }*/

  /*Future<void> getJsonFile2(url) async {
    final uri = Uri.parse(url);
    final response = await DefaultAssetBundle.of(context).loadString(uri.path);
    final data = await json.decode(response);
    print('PRINTING DATA FROM GETJSONFILE2');
    print(data['searchResults']);
  }  */

  /* Future fetchData2() async {
    fetchData(
            'https://dbc8-2804-c2c-cf03-cdb8-71a4-b78-e6ec-7cf7.ngrok-free.app/')
        .whenComplete(() => null)
        .then((value) => resultsFromJson = value);

    print('PRINTING DATA FROM FETCHDATA2');
    print(resultsFromJson);
  }*/

  Stream fetchDataFromAPI() async* {
    try {
      List data = await fetchData2(
          'http://40.76.148.166/search?q=google'); // Call the fetchData function from api_service.dart

      resultsFromJson = data;
    } catch (e) {
      print('Algo deu errado! $e');
    }
  }

  @override
  void initState() {
    fetchDataFromAPI();
    super.initState();
  }

  void _toggleTap() {
    setState(() {
      _isTapped = !_isTapped;
      if (_isTapped) {
        _isTapped1 = false;
        _isTapped2 = false;
        _isTapped3 = false;
      } else if (!_isTapped) {
        _isTapped = true;
      }
    });
  }

  void _toggleTap1() {
    setState(() {
      _isTapped1 = !_isTapped1;
      if (_isTapped1) {
        _isTapped = false;
        _isTapped2 = false;
        _isTapped3 = false;
      } else if (!_isTapped1) {
        _isTapped1 = true;
      }
    });
  }

  void _toggleTap2() {
    setState(() {
      _isTapped2 = !_isTapped2;
      if (_isTapped2) {
        _isTapped = false;
        _isTapped1 = false;
        _isTapped3 = false;
      } else if (!_isTapped2) {
        _isTapped2 = true;
      }
    });
  }

  void _toggleTap3() {
    setState(() {
      _isTapped3 = !_isTapped3;
      if (_isTapped3) {
        _isTapped = false;
        _isTapped1 = false;
        _isTapped2 = false;
      } else if (!_isTapped3) {
        _isTapped3 = true;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 20, left: 62, right: 62),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisSize: MainAxisSize.max,
              children: [
                Row(
                  children: [
                    IconButton(
                        tooltip: 'Ir para a página inicial do Bug Search',
                        onPressed: () {
                          Navigator.pushNamed(context, '/');
                        },
                        style: Theme.of(context)
                            .textButtonTheme
                            .style
                            ?.copyWith(
                              overlayColor:
                                  MaterialStateProperty.all(Colors.transparent),
                              backgroundColor:
                                  MaterialStateProperty.all(Colors.transparent),
                            ),
                        icon: const BSLogo()),
                    Text(
                      ' |',
                      style: Theme.of(context).textTheme.displayLarge,
                    ),
                    CustomSearchBar(
                        height: 48,
                        width: MediaQuery.of(context).size.width * 0.4),
                  ],
                ),
                Row(
                  children: [
                    IconButton(
                      tooltip: 'Favoritos',
                      hoverColor: Theme.of(context).colorScheme.secondary,
                      highlightColor: Theme.of(context).colorScheme.tertiary,
                      isSelected: onClick,
                      selectedIcon: const Icon(BootstrapIcons.bookmark_fill),
                      onPressed: () {
                        setState(() {
                          onClick = !onClick;
                        });
                      },
                      icon: const Icon(BootstrapIcons.bookmark),
                    ),
                    const SizedBox(width: 40),
                    customSwitchButton(
                        (p0) => {
                              setState(() {
                                isSwitched = p0;
                              })
                            },
                        isSwitched,
                        48,
                        88),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 190),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisSize: MainAxisSize.min,
              children: [
                GestureDetector(
                  behavior: HitTestBehavior.translucent,
                  onTap: _toggleTap,
                  child: Text(
                    'Todos',
                    style: Theme.of(context).textTheme.displayMedium?.copyWith(
                          fontWeight:
                              _isTapped ? FontWeight.w600 : FontWeight.w400,
                          color: _isTapped
                              ? Theme.of(context).colorScheme.primary
                              : Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                  ),
                ),
                const SizedBox(width: 16),
                GestureDetector(
                  onTap: _toggleTap1,
                  child: Text(
                    'Imagens',
                    style: Theme.of(context).textTheme.displayMedium?.copyWith(
                          fontWeight:
                              _isTapped1 ? FontWeight.w600 : FontWeight.w400,
                          color: _isTapped1
                              ? Theme.of(context).colorScheme.primary
                              : Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                  ),
                ),
                const SizedBox(width: 16),
                GestureDetector(
                  onTap: _toggleTap2,
                  child: Text(
                    'Vídeos',
                    style: Theme.of(context).textTheme.displayMedium?.copyWith(
                          fontWeight:
                              _isTapped2 ? FontWeight.w600 : FontWeight.w400,
                          color: _isTapped2
                              ? Theme.of(context).colorScheme.primary
                              : Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                  ),
                ),
                const SizedBox(width: 16),
                GestureDetector(
                  onTap: _toggleTap3,
                  child: Text(
                    'Documentos',
                    style: Theme.of(context).textTheme.displayMedium?.copyWith(
                          fontWeight:
                              _isTapped3 ? FontWeight.w600 : FontWeight.w400,
                          color: _isTapped3
                              ? Theme.of(context).colorScheme.primary
                              : Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                  ),
                ),
              ],
            ),
          ),
          Divider(
            color: Theme.of(context).colorScheme.onSurfaceVariant,
            thickness: 1,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 190),
            child: Row(
              children: [
                Text.rich(
                  TextSpan(
                    text: 'Aproximadamente ',
                    style: Theme.of(context).textTheme.titleSmall?.copyWith(
                          fontWeight: FontWeight.w600,
                          color: Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                    children: [
                      TextSpan(
                        text: 'XXX ',
                        style: Theme.of(context).textTheme.titleSmall?.copyWith(
                              fontWeight: FontWeight.w900,
                              // fontSize: 14,
                              color: Theme.of(context)
                                  .colorScheme
                                  .onSurfaceVariant,
                            ),
                      ),
                      TextSpan(
                        text: 'resultados encontrados ',
                        style: Theme.of(context).textTheme.titleSmall?.copyWith(
                              color: Theme.of(context)
                                  .colorScheme
                                  .onSurfaceVariant,
                              fontWeight: FontWeight.w600,
                            ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          // RESULTADO DA PESQUISA //
          const SizedBox(height: 20),

// ListView //

          StreamBuilder(
            stream: fetchDataFromAPI(),
            builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
              if (snapshot.hasData) {
                final resultsFromJson = snapshot.data;
                return Flexible(
                  child: resultsFromJson.isNotEmpty
                      ? ListView.builder(
                          itemCount: resultsFromJson.length,
                          itemBuilder: (BuildContext context, int index) {
                            print(resultsFromJson[index]);
                            final result = resultsFromJson[index];
                            return Column(
                              children: [
                                Text(
                                  result['title'].toString(),
                                  style: Theme.of(context)
                                      .textTheme
                                      .displayMedium
                                      ?.copyWith(
                                        fontWeight: FontWeight.w600,
                                        color: Theme.of(context)
                                            .colorScheme
                                            .onSurfaceVariant,
                                      ),
                                ),
                                Text(
                                  result[index].description,
                                  style: Theme.of(context)
                                      .textTheme
                                      .displayMedium
                                      ?.copyWith(
                                        fontWeight: FontWeight.w600,
                                        color: Theme.of(context)
                                            .colorScheme
                                            .onSurfaceVariant,
                                      ),
                                ),
                                Text(
                                  result[index].url,
                                  style: Theme.of(context)
                                      .textTheme
                                      .displayMedium
                                      ?.copyWith(
                                        fontWeight: FontWeight.w600,
                                        color: Theme.of(context)
                                            .colorScheme
                                            .onSurfaceVariant,
                                      ),
                                ),
                              ],
                            );
                          },
                        )
                      : Center(
                          child: Text(
                            'Nenhum resultado encontrado',
                            style: Theme.of(context)
                                .textTheme
                                .displayMedium
                                ?.copyWith(
                                  fontWeight: FontWeight.w600,
                                  color: Theme.of(context)
                                      .colorScheme
                                      .onSurfaceVariant,
                                ),
                          ),
                        ),
                );
              } else {
                return const Center(
                  child: CircularProgressIndicator(),
                );
              }
            },
          ),
        ],
      ),
    );
  }
}
